### PR TITLE
Add an experimental hook to Buidler EVM execution

### PR DESCRIPTION
**Pull request by alcuadrado**
This PR adds an experimental feature to Buidler and Buidler EVM. It let's plugin authors hook into Buidler EVM's low-level tracing system.

Basically, it adds a new function to the Buidler config API:

```ts
function experimentalAddBuidlerEVMMessageTraceHook(
  hook: ExperimentalBuidlerEVMMessageTraceHook
);
```

It takes a callback with this type:

```ts
export type ExperimentalBuidlerEVMMessageTraceHook = (
  bre: BuidlerRuntimeEnvironment,
  trace: MessageTrace,
  isMessageTraceFromACall: boolean
) => Promise<void>;
```

The callback is called after Buidler EVM runs transactions and calls. It's last argument let's you distinguish between those cases. 

The callback is NOT called after a tx is simulated to estimate gas costs.

I believe this is all that's needed to adapt `solidity-coverage` and `eth-gas-reporter` to work with an in-process Buidler EVM. Also, it will probably make those plugins much more performant.

This function is flagged as experimental, as I need some feedback before adding a stable version to Buidler. In particular, I think `MessageTrace#bytecode` should not be used for now.

I think this PR is specially interesting to @cgewecke, @justinjmoses, and @tranvictor.

### CODE REVIEW

**Comment by alcuadrado** [comment]
@tranvictor I believe adapting `solidity-coverage` to use this hook should be pretty straightforward. You mentioned some time ago that you were interested on helping do that. Is this still the case?

**Comment by alcuadrado** [comment]
This is an example of how to use this:

```ts
let totalGasUsed = new BN(0);

experimentalAddBuidlerEVMMessageTraceHook(
  async (bre, trace, isMessageTraceFromACall) => {
    console.log("BuidlerEVMMessageTrace:");

    if ("address" in trace) {
      console.log("  Address:", trace.address.toString("hex"));
    } else {
      console.log("  Deployment");
    }

    const executionFailed = trace.error !== undefined;
    console.log("  executionFailed?:", executionFailed)

    console.log("  gasUsed:", trace.gasUsed.toString(10))
    console.log("  isMessageTraceFromACall:", isMessageTraceFromACall)

    if (!executionFailed) {
      totalGasUsed = totalGasUsed.add(trace.gasUsed);
    }
  }
);
```

**Comment by alcuadrado** [comment]
You can install this version with:

```sh
npm install @nomiclabs/buidler@tracing
```

**Comment by cgewecke** [comment]
@alcuadrado Wow great! Thanks for this.

> Basically, it adds a new function to the Buidler config API

Could you give an example of where/how to attach the hook? 

Is `experimentalAddBuidlerEVMMessageTraceHook` settable on the outer level of the config like `paths`?

**Comment by alcuadrado** [comment]
It works just like `extendEnvironment` and `extendConfig`. You can do this in your config:

```ts
import { experimentalAddBuidlerEVMMessageTraceHook } from "@nomiclabs/buidler/config";

experimentalAddBuidlerEVMMessageTraceHook(
  async (bre, trace, isMessageTraceFromACall) => {
    console.log("BuidlerEVMMessageTrace");
  }
);
```

or this in your plugin

```ts
import { experimentalAddBuidlerEVMMessageTraceHook } from "@nomiclabs/buidler/config";

export default function () {
  experimentalAddBuidlerEVMMessageTraceHook(
    async (bre, trace, isMessageTraceFromACall) => {
      console.log("BuidlerEVMMessageTrace");
    }
  );
}

```

**Comment by alcuadrado** [comment]
The main thing I'd like your feedback on is how much of `MessageTrace` should be made public, and if it is missing something useful. It is now an internal API, and it's not very intuitive how to use it.

This method does something similar to what `solidity-coverage` and `eth-gas-reporter` would do with it: https://github.com/nomiclabs/buidler/blob/development/packages/buidler-core/src/internal/buidler-evm/stack-traces/consoleLogger.ts#L95

**Comment by alcuadrado** [comment]
@scnale and @jcaracciolo you may also find this useful.

**Comment by justinjmoses** [comment]
Definitely looks intriguing. I will check this out when I have a bit of time early next week

**Review by fvictorio — APPROVED** [review]

**Pull request merged**
