### PR TITLE
Add Binance Smart Chain to Etherscan prober

### PR DESCRIPTION
**Pull request by Dominator008**

### CODE REVIEW

**Comment by alcuadrado** [comment]
Hey @Dominator008,

Thanks for submitting this PR.

As it doesn't have any new tests, how can we make sure that this works? Does bscscan runs the exact same backend than etherscan?

**Comment by Dominator008** [comment]
Unfortunately it doesn't work as of now. bscscan doesn't have the verification API.

**Comment by alcuadrado** [comment]
So I guess we shouldn't merge this yet. It would be confusing for the plugin users otherwise.

**Comment by Dominator008** [comment]
Yeah. Will need to wait until they enable that API.

**Comment by fvictorio** [comment]
I'm closing this for housekeeping, but please feel free to re-open it when the API is available.

**Pull request closed without merging**
