### PR TITLE
sendAsync support to make it compatible with ethers by default

### PR DESCRIPTION
**Pull request by wighawag**

### CODE REVIEW

**Comment by wighawag** [comment]
Main reason to have that as part of the core, is that else without that plugin like https://github.com/sc-forks/solidity-coverage need to support ethers when they create the provider (see https://github.com/sc-forks/solidity-coverage/blob/d6b86fa3870238fefcb7ff33f9978a2ec2e8a29d/plugins/resources/buidler.utils.js#L55)

**Comment by alcuadrado** [comment]
Really interesting PR, @wighawag!

Does this change mean that we'd be able to do `new ethers.providers.Web3Provider(bre.network.provider)`?

**Comment by wighawag** [comment]
Yes, exactly

**Comment by alcuadrado** [comment]
I'm closing this, as the next version will already include `sendAsync`.

**Pull request closed without merging**
