### PR TITLE
Add Full Solidity Settings configuration

### PR DESCRIPTION
**Pull request by wighawag**
Currently buidler limit solidity settings by specifying which fields are passed through.
This PR allow user to pass teh full settings object in the solc config object.

The PR remains backward compatible.

It also add the metadata field in the output artifact but I wonder if the artifact should not include the full solidity output. 

This would duplicate some info if we want it to be backward compatible though.

### CODE REVIEW

**Comment by alcuadrado** [comment]
Thanks for this PR. It looks good. 

I'm not merging it yet, as we want to release a new version on Monday and don't have enough time to properly review it yet. Will get back to it after this release.

**Comment by wighawag** [comment]
I updated with lint fixes and made metadata a basic option.
and the solcSettings now will now output the full solc output when outputSelection is set.

**Comment by kendricktan** [comment]
Any updates on this?

**Comment by alcuadrado** [comment]
Thanks for this PR, Ronan. 

We are working on redesigning the compilation pipeline, so I'm hesitant about merging and releasing this, as it may make that other work harder.

Please take a look at #553

**Comment by wighawag** [comment]
Hey if we cannot get the full solc setting in right now, maybe we could get a  least the metadata output. this is pretty important for my use case, this should be a minimal change : adding metadata to the output here https://github.com/nomiclabs/buidler/blob/f78562ab85d74fc2ad56292511273f6e974f1487/packages/buidler-core/src/internal/artifacts.ts#L46

Could make a simpler PR that only add metadata option so we can get inline metadata ?

**Comment by wighawag** [comment]
Created a PR that simply output the metadata in the artifact (like mentioned above) : https://github.com/nomiclabs/buidler/pull/668

**Comment by alcuadrado** [comment]
Thanks for these PRs @wighawag. This feature will be available in the next version of Buidler. I'm closing this PR because the actual implementation, which supports multiple solc versions within the same project, is much more complex.

**Pull request closed without merging**
