### PR TITLE
Enable node 12 in travis ci

### PR DESCRIPTION
**Pull request by alcuadrado**

### CODE REVIEW

**Comment by filips123** [comment]
Truffle and its sub-packages (`truffle-contract`) are unusable on Node.js 12 (trufflesuite/truffle#2070). Because of that, this package is also unusable on Node.js 12.

**Comment by alcuadrado** [comment]
Hey @filips123! Thanks for taking the time to report this here and in Truffle's repo. 

As gnidan mentioned in the issue you linked, it's a complicated situation because of web3. 

This situation shouldn't last much longer, as we are coordinating a fix with web3, truffle, and a few more teams.

**Comment by alcuadrado** [comment]
In the meantime, I recommend using https://github.com/nvm-sh/nvm

**Comment by alcuadrado** [comment]
Already enabled in #349

**Pull request closed without merging**
