### PR TITLE
Artifact metadata

### PR DESCRIPTION
**Pull request by wighawag**
this output the metadata to the artifact

### CODE REVIEW

**Comment by alcuadrado** [comment]
Hey @wighawag can you explain us a bit more about the use-case here?

We are actively working on #553 now, so we want to take this into consideration

**Comment by wighawag** [comment]
the main thing I need is access to metadata so I can save the exact source the contract was compiled in. I can then use that t verify on etherscan or other.

This PR does the minimal change to get that in

**Comment by chriseth** [comment]
The metadata is one of the main things that need to be preserved after compilation. Without it, it is very difficult if not impossible to re-compile and thus verify contracts. I think this deserves to be merged even without the overhaul in the compilation process.

**Comment by alcuadrado** [comment]
Hey @wighawag, I'm closing this PR, as the output will now be stored entirely, as I mentioned on our call last week. Thanks for sending the PR anyway.

**Pull request closed without merging**
