### PR TITLE
docs: fix broken link to tasks docs

### PR DESCRIPTION
**Pull request by PaulRBerg**
The [previous link](https://buidler.dev/advanced/buidler-runtime-environment.html#creating-your-own-tasks) wasn't redirecting the user anywhere.

### CODE REVIEW

**Comment by PaulRBerg** [comment]
Also, if we are discussing about this page, what does "DSL" mean?

> You can import the config DSL explicitly when defining your tasks, and receive the BRE explicitly as an argument to your actions.

**Comment by fzeoli** [comment]
> Also, if we are discussing about this page, what does "DSL" mean?
> 
> > You can import the config DSL explicitly when defining your tasks, and receive the BRE explicitly as an argument to your actions.

https://en.wikipedia.org/wiki/Domain-specific_language

**Comment by alcuadrado** [comment]
We should probably stop using DSL. What do you think about `config API`, @PaulRBerg ?

**Comment by PaulRBerg** [comment]
Oh, thanks @fzeoli! I missed that. The first results on DuckDuckGo pointed to "Digital Subscriber Line", which seemed totally unrelated.

@alcuadrado, "config API" sounds better, but DSL is also good if you unpack it. When I see an acronym on the Internet, I tap "CMD + F" and look for the first reference for that acronym, since it usually unpacks all words.

**Pull request merged**
