### PR TITLE
Migrate to ethers v5

### PR DESCRIPTION
**Pull request by pedrouid**
Fix #534 

I thought I would contribute to migrating to ethers v5.x earlier by submitting a PR. Most of the API changes were pretty straightforward and there weren't any critical complications. Changes include updating ethers and typescript since Typescript was outdated related to ethers typings

All the tests are passing except one which was skipped, however there are two issues that should be investigated so I commented with FIXME notes:

1) lazyFunction<T extends Function> wasn't injecting types correctly because of the Typescript upgrade (temporarily solved by type casting functionCreator)
2) error_please test for ethers-provider-wrapper was failling deepEqual although the error messages looked very similar (temporarily solved by skipping test)

### CODE REVIEW

**Comment by pedrouid** [comment]
It would be great to publish a pre-release of this PR once merged so that is accessible on NPM at least until ethers v5 drops the beta

cc @alcuadrado @fzeoli

**Comment by alcuadrado** [comment]
I merged this into `buidler-ethers-v5` so I can release an alpha version as `@next`

**Comment by alcuadrado** [comment]
I just released `@nomiclabs/buidler-ethers@next` and  `@nomiclabs/buidler-waffle@next`. Please use them with care, as they are experimental versions, and breaking changes will happen.

**Comment by rhlsthrm** [comment]
Thanks a ton @alcuadrado!

**Pull request merged**
